name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: parse
      uses: ./
      with:
        sqs-queue-url: https://sqs.us-east-1.amazonaws.com/111111111111/test
    - run: "echo aws-account-id: ${{ steps.parse.outputs.aws-account-id }}"
    - run: "echo aws-region: ${{ steps.parse.outputs.aws-region }}"
    - run: "echo sqs-queue-name: ${{ steps.parse.outputs.sqs-queue-name }}"
